### PR TITLE
Fix merge conflicts with origin.

### PR DESCRIPTION
**Pull request by tokejepsen**

### CODE REVIEW

**Comment by BigRoy** [comment]
This seems to be removing some Fusion files that we should actually keep. Is the Github change files view correct that those files will get removed with this PR?

**Comment by tokejepsen** [comment]
You are right!

That is fixed now. Have really messed up on the commits, so let me know if you think this is no good.

**Comment by BigRoy** [comment]
@aardschok do you know why this has [these lines](https://github.com/Colorbleed/core/pull/22/files#diff-387f88ae931d9d3d95d9df5d39e20211R7) that are somehow not in our master? :)

**Comment by aardschok** [comment]
Because it works without those lines as well? It's up and running here without them.

**Comment by BigRoy** [comment]
> Because it works without those lines as well? It's up and running here without them.

Haha. No the functionality in those lines was implemented for something, right? :) I meant, how come it's not in our code but it did end up here? Did we remove it at some point? If so, then this PR will put it back in which would be wrong. If it's _not yet!_ in our master then I guess this PR shouldn't be putting it there either - right?

Somehow this PR has that code, but I'm not sure why or how? :)

**Comment by tokejepsen** [comment]
Think this PR might be doing more harm than good.

The actual merge conflicts were very quick to do, so it might be better for you guys to do it yourself.

**Comment by aardschok** [comment]
@BigRoy has a look at the `origin` and I did add the `self` variable to the `avalon.core` but somewhere that change never made it to ours :sweat_smile:

**Comment by BigRoy** [comment]
What origin? :) 

- The avalon core doesn't even have the Fusion folder? https://github.com/getavalon/core/tree/master/avalon 
- Colorbeed/core master doesn't have those lines: https://github.com/Colorbleed/core/blob/master/avalon/fusion/pipeline.py
- Aardschok/core master doesn't have those lines: https://github.com/aardschok/core/blob/master/avalon/fusion/pipeline.py

**Comment by BigRoy** [comment]
Swapping this with another one: https://github.com/Colorbleed/core/pull/24

**Pull request closed without merging**
